"""open/close_application name resolution and the tool log's ok flag --
nothing here launches or kills a real process."""

from __future__ import annotations

import asyncio
import json

import psutil
import pytest

from tools import app_launcher as L
from tools import system
from tools._logging import log_call

FAKE_START_APPS = [
    (L._squash(name), name, app_id)
    for name, app_id in [
        ("Discord", "com.squirrel.Discord.Discord"),
        ("Paint", "Microsoft.Paint_8wekyb3d8bbwe!App"),
        ("Counter-Strike 2", "steam://rungameid/730"),
        ("Диспетчер задач", "Microsoft.AutoGenerated.{600A9E7E}"),
        ("Paint.NET", "dotPDN.PaintDotNet"),
    ]
]


@pytest.fixture
def start_apps(monkeypatch):
    monkeypatch.setattr(L, "_start_apps", list(FAKE_START_APPS))
    monkeypatch.setattr(L, "_SYSTEM", "Windows")


@pytest.mark.parametrize("query, expected", [
    ("Paint", "Microsoft.Paint_8wekyb3d8bbwe!App"),
    ("discord", "com.squirrel.Discord.Discord"),
    ("counter strike", "steam://rungameid/730"),      # prefix, punctuation-insensitive
    ("диспетчер задач", "Microsoft.AutoGenerated.{600A9E7E}"),
    ("paint.net", "dotPDN.PaintDotNet"),
])
def test_find_start_app(start_apps, query, expected):
    assert L._find_start_app(query)[1] == expected


def test_short_partial_query_matches_nothing(start_apps):
    assert L._find_start_app("pa") is None


def test_web_services_go_to_browser(start_apps):
    assert L._web_url("YouTube") == "https://www.youtube.com"
    assert L._web_url("ютуб") == "https://www.youtube.com"
    assert L._web_url("vk.com") == "https://vk.com"
    assert L._web_url("Discord") is None
    assert L._web_url("AfterFX.exe") is None


def test_installed_pwa_beats_website(start_apps, monkeypatch):
    opened = []
    monkeypatch.setattr("webbrowser.open", lambda url: opened.append(url) or True)
    monkeypatch.setitem(L._OS_LAUNCHERS, "Windows", lambda name: True)
    ok, message = L._launch_sync("YouTube")
    assert ok and opened == ["https://www.youtube.com"] and "браузере" in message

    opened.clear()
    ok, _ = L._launch_sync("paint.net")  # installed app with a domain-like name
    assert ok and opened == []


def test_alias_matches_whole_words_only():
    assert L._normalize("google chrome browser") == "chrome"
    assert L._normalize("paint.net") == "paint.net"


@pytest.mark.parametrize("spoken, hint", [
    ("гугл", "chrome"),
    ("Taskmgr.exe", "taskmgr"),
    ("диспетчер задач", "taskmgr"),
    ("ворд", "winword"),
    ("Discord", "discord"),
])
def test_close_hint(spoken, hint):
    assert system._find_process_hint(spoken) == hint


class _ElevatedProc:
    pid = 999_999
    info = {"pid": 999_999, "name": "Taskmgr.exe"}

    def terminate(self):
        raise psutil.AccessDenied(self.pid)


def test_close_elevated_app_reports_error(monkeypatch):
    monkeypatch.setattr(psutil, "process_iter", lambda attrs=None: [_ElevatedProc()])
    monkeypatch.setattr(psutil, "wait_procs", lambda procs, timeout=None: ([], list(procs)))
    result = asyncio.run(system._close_application(name="диспетчер задач"))
    assert result["status"] == "error" and "администратора" in result["message"]


def test_status_error_logged_as_failure(isolated_data):
    @log_call("fake_tool")
    async def fake(**_):
        return {"status": "error", "message": "nope"}

    @log_call("fine_tool")
    async def fine(**_):
        return {"status": "ok"}

    asyncio.run(fake())
    asyncio.run(fine())
    entries = [json.loads(line) for line in (isolated_data / "tool_calls.log").read_text("utf-8").splitlines()]
    assert [(e["tool"], e["ok"]) for e in entries] == [("fake_tool", False), ("fine_tool", True)]
