"""
actions/scheduled_send.py — schedule a Telegram message to be sent later.

Reuses the same OS task-scheduling machinery as actions/reminder.py
(Task Scheduler on Windows, launchd on mac, systemd-run/at on Linux), but
instead of showing a notification, the generated script connects to the
Telegram userbot session (integrations/telegram_userbot.py) and sends the
message itself. This means the message goes out at the scheduled time even
if JARVIS isn't running at that moment — only the second Telegram account's
saved session and Telethon need to be present.

Only the "telegram"/"tg" platform is supported for scheduled sending —
GUI-automated platforms (WhatsApp etc.) aren't reliable to fire unattended.
"""
import json
from datetime import datetime
from pathlib import Path

from actions.reminder import (
    _get_os, _scripts_dir,
    _schedule_windows, _schedule_mac, _schedule_linux,
)

_MAX_MESSAGE_LEN = 4000
_PROJECT_ROOT    = Path(__file__).resolve().parent.parent


def _write_telegram_send_script(task_name: str, receiver: str, message: str) -> Path:
    script_path      = _scripts_dir() / f"{task_name}.py"
    receiver_literal = json.dumps(receiver)
    message_literal  = json.dumps(message)
    project_literal  = json.dumps(str(_PROJECT_ROOT))

    script_body = f'''# Auto-generated by J.A.R.V.I.S — scheduled Telegram send. Do not edit.
import asyncio, json, os, pathlib, sys

sys.path.insert(0, {project_literal})

RECEIVER = {receiver_literal}
MESSAGE  = {message_literal}

appdata      = os.getenv("APPDATA") or str(pathlib.Path.home())
cfg_path     = pathlib.Path(appdata) / "Jarvis" / "api_keys.json"
session_path = str(pathlib.Path(appdata) / "Jarvis" / "telegram_userbot")

def _cfg():
    try:
        return json.loads(cfg_path.read_text(encoding="utf-8"))
    except Exception:
        return {{}}

async def _send():
    from telethon import TelegramClient
    from integrations.telegram_userbot import resolve_contact
    cfg      = _cfg()
    api_id   = cfg.get("telegram_api_id")
    api_hash = cfg.get("telegram_api_hash")
    if not api_id or not api_hash:
        return
    client = TelegramClient(session_path, int(api_id), api_hash)
    await client.connect()
    try:
        if await client.is_user_authorized():
            entity, _ambiguous = await resolve_contact(client, RECEIVER)
            if entity is not None:
                await client.send_message(entity, MESSAGE)
    finally:
        await client.disconnect()

try:
    asyncio.run(_send())
except Exception:
    pass

try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
'''
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)
    return script_path


def schedule_message(parameters: dict, player=None) -> str:
    params       = parameters or {}
    receiver     = params.get("receiver", "").strip()
    message_text = params.get("message_text", "").strip()
    platform     = (params.get("platform") or "telegram").strip().lower()
    date_str     = params.get("date", "").strip()
    time_str     = params.get("time", "").strip()

    if not receiver:
        return "Please specify a recipient."
    if not message_text:
        return "Please specify the message content."
    if not date_str or not time_str:
        return "I need both a date and a time to schedule this message."
    if platform not in ("telegram", "tg"):
        return (
            f"Scheduled sending is only supported for Telegram right now, not {platform}. "
            "I can send it immediately instead."
        )

    try:
        target_dt = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
    except ValueError:
        return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM."

    if target_dt <= datetime.now():
        return "That time has already passed — I can't schedule a message in the past."

    os_name   = _get_os()
    safe_msg  = message_text[:_MAX_MESSAGE_LEN]
    task_name = f"JARVISTelegramSend_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    try:
        script_path = _write_telegram_send_script(task_name, receiver, safe_msg)
    except Exception as e:
        return f"Could not prepare the scheduled message script: {e}"

    try:
        if os_name == "windows":
            job_id = _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        script_path.unlink(missing_ok=True)
        return f"Something went wrong while scheduling the message: {e}"

    if not job_id:
        return "I couldn't register the scheduled message with the system scheduler."

    if player:
        player.write_log(f"[Telegram] Scheduled -> {receiver} @ {date_str} {time_str}")

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    return f"Message to {receiver} scheduled for {friendly_time} via Telegram."
